// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5J4gri3vAvwDyfFD5bdeHKhApVI-5e70',
    appId: '1:671900172138:web:787fa529cf2a5b495e6f13',
    messagingSenderId: '671900172138',
    projectId: 'amacle-hotel-web-new',
    authDomain: 'amacle-hotel-web-new.firebaseapp.com',
    storageBucket: 'amacle-hotel-web-new.appspot.com',
    measurementId: 'G-78ZMRC98Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDId9qgO-dr3lc8xF_bhJ4DILKgTK0Xr1A',
    appId: '1:671900172138:android:ef6d0b23aee3e7235e6f13',
    messagingSenderId: '671900172138',
    projectId: 'amacle-hotel-web-new',
    storageBucket: 'amacle-hotel-web-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFmvgaT0KiaTy--q266AC6SLPSEUKLLtY',
    appId: '1:671900172138:ios:08e014785947fe1d5e6f13',
    messagingSenderId: '671900172138',
    projectId: 'amacle-hotel-web-new',
    storageBucket: 'amacle-hotel-web-new.appspot.com',
    iosClientId: '671900172138-ame9f8fqas11vcddlc9kfphueq1jfire.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHotelManagementWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFmvgaT0KiaTy--q266AC6SLPSEUKLLtY',
    appId: '1:671900172138:ios:446bdafb9749067f5e6f13',
    messagingSenderId: '671900172138',
    projectId: 'amacle-hotel-web-new',
    storageBucket: 'amacle-hotel-web-new.appspot.com',
    iosClientId: '671900172138-fkm2ui4fm9rv282iea42dsa5d70hggt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHotelManagementWebapp.RunnerTests',
  );
}
